epsilon: 1.0
e_max_step: 4000
min_e: 0.01
gamma: 0.95
alpha: 0.9
nepisodes: 5000
seed: 1
max_steps: 500
batch_size: 64
device: cpu
memorysize: 100000
lr: 0.01793531454588457
use_wandb: False
nUnits: [64,64,64]
start_training_step: 4
num_eval_episodes: 5
eval_freq: 20
update_freq: 4
